### ISSUE TITLE
Cannot convert undefined to null to object

### ISSUE THREAD

**Issue by seanyu4296** [xouabita/razzle-heroku#3]
I'm getting this error Cannot convert undefined to null to object

it seems to fail in this line
```
entries(definitions['process.env']).forEach(writeDefs);
```
definitions['process.env'] is undefined

definitions has this value
```
{
'process.env.NODE_ENV': '"production"',
  'process.env.PORT': '3000',
  'process.env.VERBOSE': 'false',
  'process.env.HOST': '"localhost"',
}
```

**Comment by cultofmetatron** [comment]
seconded, I'm running into this issue myself and cannot get it running on heroku

**Comment by erchaves** [comment]
Ahhh, I realized that I was getting this error because I was using this with Razzle 2 and this is not compatible yet. (i'm using razzle 2.2.0)

There is a PR that fixes this issue for me: (Upgrade for compatibility with Razzle 2 #4
)[https://github.com/xouabita/razzle-heroku/pull/4]. 

For now, I just pulled down mrwade's branch and that's working for me. Thanks @mrwade!

**Comment by xouabita** [comment]
Hi guys, I merged the PR. It should work now
